/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AssessmentRouteImport } from './routes/assessment'

const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/assessment': typeof AssessmentRoute
}
export interface FileRoutesByTo {
  '/assessment': typeof AssessmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/assessment': typeof AssessmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/assessment'
  fileRoutesByTo: FileRoutesByTo
  to: '/assessment'
  id: '__root__' | '/assessment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AssessmentRoute: typeof AssessmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AssessmentRoute: AssessmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
